export enum TILE_TYPE_ENUM {
  WALL_ROW = 'WALL_ROW', // 横墙
  WALL_COLUMN = 'WALL_COLUMN', // 竖墙
  WALL_LEFT_TOP = 'WALL_LEFT_TOP', // 左上角
  WALL_LEFT_BOTTOM = 'WALL_LEFT_BOTTOM', // 左下角
  WALL_RIGHT_TOP = 'WALL_RIGHT_TOP', // 右上角
  WALL_RIGHT_BOTTOM = 'WALL_RIGHT_BOTTOM', // 右下角
  CLIFF_CENTER = 'CLIFF_CENTER', // 悬崖中
  CLIFF_LEFT = 'CLIFF_LEFT', // 悬崖左
  CLIFF_RIGHT = 'CLIFF_RIGHT', // 悬崖右
  FLOOR = 'FLOOR' // 地板
}

export enum EVENT_ENUM {
  NEXT_LEVEL = 'NEXT_LEVEL',
  PLAYER_MOVE_END = 'PLAYER_MOVE_END',
  ATTACK_PLAYER = 'ATTACK_PLAYER',
  ATTACK_ENEMY = 'ATTACK_ENEMY',
  PLAYER_CTRL = 'PLAYER_CTRL'
}

export enum CONTROLLER_ENUM {
  TOP = 'TOP',
  BOTTOM = 'BOTTOM',
  LEFT = 'LEFT',
  RIGHT = 'RIGHT',
  TURNLEFT = 'TURNLEFT',
  TURNRIGHT = 'TURNRIGHT'
}

export enum FMS_PARAMS_TYPE_ENUM {
  NUMBER = 'NUMBER',
  TRIGGER = 'TRIGGER'
}

export enum PARAMS_NAME_ENUM {
  IDLE = 'IDLE',
  ATTACK = 'ATTACK',
  TURNLEFT = 'TURNLEFT',
  TURNRIGHT = 'TURNRIGHT',
  BLOCKFRONT = 'BLOCKFRONT',
  BLOCKBCAK = 'BLOCKBCAK',
  BLOCKLEFT = 'BLOCKLEFT',
  BLOCKRIGHT = 'BLOCKRIGHT',
  BLOCKTURNLEFT = 'BLOCKTURNLEFT',
  BLOCKTURNRIGHT = 'BLOCKTURNRIGHT',
  DIRECTION = 'DIRECTION',
  DEATH = 'DEATH',
  AIRDEATH = 'AIRDEATH',
}

export enum DIRECTION_ENUM {
  TOP = 'TOP',
  BOTTOM = 'BOTTOM',
  LEFT = 'LEFT',
  RIGHT = 'RIGHT',
}

export enum ENTITY_STATE_ENUM {
  IDLE = 'IDLE',
  ATTACK = 'ATTACK',
  TURNLEFT = 'TURNLEFT',
  TURNRIGHT = 'TURNRIGHT',
  BLOCKFRONT = 'BLOCKFRONT',
  BLOCKBCAK = 'BLOCKBCAK',
  BLOCKLEFT = 'BLOCKLEFT',
  BLOCKRIGHT = 'BLOCKRIGHT',
  BLOCKTURNLEFT = 'BLOCKTURNLEFT',
  BLOCKTURNRIGHT = 'BLOCKTURNRIGHT',
  DEATH = 'DEATH',
  AIRDEATH = 'AIRDEATH',
}

export enum DIRECTION_ORDER_ENUM {
  TOP = 0,
  BOTTOM = 1,
  LEFT = 2,
  RIGHT = 3,
}